image: proboci/ubuntu-16.04-lamp:php-7.2
steps:
  - name: Probo Grav site initialization.
    plugin: LAMPApp
  - name: Download Concrete 5 latest release.
    plugin: Script
    script: |
      composer create-project getgrav/grav /tmp/src --no-interaction
      cp -Rf /tmp/src/* /src
  - name: Creating required directories and setting permissions.
    plugin: Script
    script: |
      mkdir /src/logs /src/images /src/assets /src/user/data
      chown -R www-data:www-data .
      find ./bin -type f | xargs chmod 775
      find . -type d | xargs chmod 775
      find . -type d | xargs chmod +s
      echo "testing 123"
