image: proboci/ubuntu-16.04-lamp:php7.2-nightly
steps:
  - name: Update composer
    command: '/usr/local/bin/composer self-update'
  - name: Probo site setup
    plugin: LAMPApp
  - name: Set permissions
    plugin: Script
    script:
      - find ./bin -type f | xargs chmod 775
      - find . -type d | xargs chmod 775
      - find . -type d | xargs chmod +s
